name: Snapshot Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  frontend_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - name: Install Yarn
        run: |
          yarn
      - name: Run Unit Tests in CI
        run: |
          yarn test:ci
      - name: Build the Project
        run: |
          touch .env
          echo ADMIN_ID=${{ secrets.ADMIN_ID }} >> .env
          echo RANDOM_INIT_STRING=${{ secrets.RANDOM_INIT_STRING }} >> .env
          echo RANDOM_TASK_ID=${{ secrets.RANDOM_TASK_ID }} >> .env
          yarn test:ci
          yarn build